"""rename category

Revision ID: cd59a5fcbe8c
Revises: d2e5110010c9
Create Date: 2024-06-28 10:36:11.791486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd59a5fcbe8c'
down_revision = 'd2e5110010c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('category', 'categories')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('categories', 'category')
    # ### end Alembic commands ###
